alias: 'HVAC Auto Pause/Resume - Door & Window with Grace Periods'
mode: restart  ## Only one instance runs, cancels prior ones if retriggered
triggers:
  - platform: event
    event_type: sia_event
    event_data:
      code: 'BA' ##Burglary Alarm
      ri: 7  ## DoorProtect - Window or Door opened
    id: door_opened
  - platform: event
    event_type: sia_event
    event_data:
      code: 'BR' ##Alarm Restored
      ri: 7  ## DoorProtect - Window or Door closed
    id: door_closed
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: door_opened
        sequence:
          - delay: "00:05:00"  # Wait 5 minutes to check door/window state
          - wait_for_trigger:
              - platform: event
                event_type: sia_event
                event_data:
                  code: 'BR'
                  ri: 2  ## Door/Window closed
            timeout: "00:00:01"  # Immediately check after delay
            continue_on_timeout: true
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ wait.trigger is none }}" ##check if wait period expired
                sequence:
                  - service: climate.set_hvac_mode
                    target:
                      entity_id: climate.living_room
                    data:
                      hvac_mode: 'off'
                  - service: tts.speak
                    metadata: {}
                    data:
                      cache: true
                      media_player_entity_id: media_player.living_room_speaker
                      message: "HVAC paused. Door or Window remained open for over 5 minutes."
                    target:
                      entity_id: tts.google_en_com

      - conditions:
          - condition: trigger
            id: door_closed
        sequence:
          - delay: "00:05:00"  ## Grace period after door closes
          - wait_for_trigger:
              - platform: event
                event_type: sia_event
                event_data:
                  code: 'BA'
                  ri: 2  ## Door opened again
            timeout: "00:00:01"
            continue_on_timeout: true
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ wait.trigger is none }}"
                sequence:
                  - service: climate.set_hvac_mode
                    target:
                      entity_id: climate.living_room
                    data:
                      hvac_mode: 'heat'  ## Adjust mode as needed
                  - service: tts.speak
                    metadata: {}
                    data:
                      cache: true
                      media_player_entity_id: media_player.living_room_speaker
                      message: "HVAC resumed. Door stayed closed for 5 minutes."
                    target:
                      entity_id: tts.google_en_com
